### ISSUE TITLE
Error 7.2.1 Template.SimpleTemplate - legacy template expected, but not found

### ISSUE THREAD

**Issue by mandiwhite** [DNNCommunity/DNN.Announcements#53] opened 2020-07-21 01:17 UTC
## Please summarize your question in one sentence
Errors reported several times per hour 'legacy template expected' and 'settingname empty'. Need help finding the cause.

## Give a more extended description
Error: "DotNetNuke.Modules.Announcements.Components.Template.SimpleTemplate - legacy template expected, but not found, settingName: header.htm, loading new style template"
Error: "DotNetNuke.Modules.Announcements.Components.Template.SimpleTemplate - error loading template, settingname empty"
## Steps to reproduce (if needed)
I don't know what caused these error to start happening. Is there a way to narrow down if it's just 1 or 2 Announcements modules that are causing this?

## Other comments or remarks
I modified the Simple Template by removing [READMORE] and making the title the link to the uploaded document.

**Comment by valadas** [comment] 2020-07-30 01:09
I am closing this issue as I cannot reproduce the problem. 

If this is still not resolved, please reopen a new issue and follow the issue template exactly. Clear steps to reproduce, Dnn and module version, etc.

**Closed by valadas** 2020-07-30 01:09 UTC
