### ISSUE TITLE
Error with 7.02.00 on DNN 9.2

### ISSUE THREAD

**Issue by mattmol** [DNNCommunity/DNN.Announcements#12] opened 2018-06-07 21:47 UTC
AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:1b3183b6-136d-4eca-bbc0-895ad5812c54

AssemblyVersion:9.2.0

PortalId:0

UserId:1

TabId:76

Message:Object reference not set to an instance of an object.

StackTrace:

InnerMessage:Object reference not set to an instance of an object.

InnerStackTrace:

at DotNetNuke.Modules.Announcements.Components.Business.AnnouncementInfo.GetProperty(String strPropertyName, String strFormat, CultureInfo formatProvider, UserInfo AccessingUser, Scope AccessLevel, Boolean& PropertyNotFound) at DotNetNuke.Services.Tokens.BaseCustomTokenReplace.replacedTokenValue(String objectName, String propertyName, String format) at DotNetNuke.Services.Tokens.BaseTokenReplace.ReplaceTokens(String sourceText) at DotNetNuke.Modules.Announcements.Components.Template.SimpleTemplate.RenderTemplate(IEnumerable`1 announcements, Boolean editEnabled) at DotNetNuke.Modules.Announcements.MVP.Presenters.AnnouncementsViewPresenter.GetRenderedTemplate(Object sender, EventArgs e) at DotNetNuke.Modules.Announcements.AnnouncementsView.OnLoad(EventArgs e) at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

**Comment by valadas** [comment] 2018-06-11 04:28
It look like a token replace issue, can you post your template in use, there might be something wrong with an invalid token or something. Also, was this upgraded (if so please let us know from which version) so we can test further... Thanks.

**Comment by mattmol** [comment] 2018-06-12 02:44
I can't access it without reverting my site :(  http://www.ralphwilliams.com/Home/Post/431/The-Announcements-Module-and-jQuery-as-an-Accordion  It was a jquery accordion like this though.

It was updated from 4.03

**Comment by mattmol** [comment] 2018-06-12 02:59
Figured out how to access some of it...
Under "Announcement Settings" it was -1 for  History(days).
I change to 0 and nothing is there.. but the error goes away.
When I check the template, the template seems like it loaded a default template...

**Comment by mattmol** [comment] 2018-06-12 03:01
<div class="DNN_ANN_DesignTable">

<div class="DNN_ANN_ImageDiv">[IMAGESOURCE]</div>
<div><h3>[EDIT][TITLE] - [PUBLISHDATE]</h3><div class="Normal">[DESCRIPTION]&nbsp;[READMORE]</div>
</div>


This is what is in there... but that's not the template I had in there before....

**Comment by mattmol** [comment] 2018-06-12 03:18
OK... so it's fixed.  The problem was the default template (above) that replaced my template.
I was able to find my original template by finding the module ID and searching for the dbo.ModuleSettings table in the database.

The correct template was listed under "Template"
I copied and pasted that into the module, and it worked. (Along with header template)

**Comment by mattmol** [comment] 2018-06-12 03:19
SELECT [ModuleID]
      ,[SettingName]
      ,[SettingValue]
      ,[CreatedByUserID]
      ,[CreatedOnDate]
      ,[LastModifiedByUserID]
      ,[LastModifiedOnDate]
  FROM [**DATABASENAME**].[dbo].[ModuleSettings]
  where ModuleID=**moduleIDnumber**

**Comment by valadas** [comment] 2018-06-12 18:09
Ok, @mattmol  glad it is resoveld.

I don't know what changed the template please close this issue if you cant reproduce or provide clear steps to reproduce if you think this is consistently reproducible.
Thanks.

**Comment by valadas** [comment] 2018-06-15 07:35
@EPTamminga can you please close this issue. Thanks.

**Closed** 2018-06-15 13:38 UTC
