### ISSUE TITLE
General Exception in Announcements running DNN 9.2.2 and Announcements 7.2.1

### ISSUE THREAD

**Issue by thosalbert** [DNNCommunity/DNN.Announcements#37] opened 2019-10-02 18:44 UTC
Hi, I'm seeing a General Exception in Announcements running DNN 9.2.2 and Announcements 7.2.1. The module instances are working.

Here's the error, Let me know if there's anything I can do..Thanks

Tom

General Exception
**AbsoluteURL:**
**DefaultDataProvider:**DotNetNuke.Data.SqlDataProvider, DotNetNuke
**ExceptionGUID:**7588c350-2701-4adf-a4a7-cc0946ca1ad8
**AssemblyVersion:**
**PortalId:**-1
**UserId:**-1
**TabId:**-1
**RawUrl:**
**Referrer:**
**UserAgent:**
**ExceptionHash:**9dnvQmo3Pny3KTtYGiG0qDSebiI=
**Message:**Object reference not set to an instance of an object.
**StackTrace:**
at DotNetNuke.Modules.Announcements.Components.Business.AnnouncementsController.GetModifiedSearchDocuments(ModuleInfo moduleInfo, DateTime beginDateUtc) at DotNetNuke.Services.Search.ModuleIndexer.IndexSearchDocuments(Int32 portalId, ScheduleHistoryItem schedule, DateTime startDateLocal, Action`1 indexer)
**InnerMessage:**
**InnerStackTrace:**
Source:DotNetNuke.Modules.Announcements
**FileName:**
**FileLineNumber:**0
**FileColumnNumber:**0
**Method:**
**Server Name:** SCTAS35

**Comment by thosalbert** [comment] 2019-10-08 21:54
Hi again - 
I've started over in my upgrade testing, and working on DNN 9.1.1 (preparing to upgrade) I upgraded the Announcement module to v 7.2.1, and I'm seeing the same error coming up in Admin Logs. 
Basically the same as in my message above. Any idea what is causing this? 

Thanks

Tom

**Comment by valadas** [comment] 2019-10-09 07:10
A lot of those older modules where migrated from VB to C# and the value types are a bit more strict in C#, as a first step to figure out if my assumption is right, does this only happen with modules having existing data?

If you put a new instance on a temporary page and create new data, do you have the same problem?

Then I would compare in the database Annoncements table for differences between NULL and empty strings, this is kinda common and hard to test without old data that goes with it.

Let us know...

**Comment by thosalbert** [comment] 2019-10-09 17:59
Thanks Valadas - 

In this case, I'm seeing the General Exceptions in Admin Logs, even if I haven't visited any page with an Announcements module (This is on a test website - I'm the only one browsing it).  I just start the website and pretty soon the errors start appearing, even if the only page I browse is the Homepage (with no Announcements module) and Admin Logs.

I did have a look at the database (based on your help with the Links module) , and comparing the older working version and the new version, I don't see anything obvious that looks like it should be changed (the newer version has a few more columns and a new table). 

Thanks -  Let me know what you think.

-Tom

**Comment by thosalbert** [comment] 2019-10-11 21:43
Strange that it's throwing an error even if I don't access the page with the module instance. Has anyone else seen this?

Thanks

Tom

**Comment by valadas** [comment] 2019-10-14 11:44
Well, this particular error relates to the search indexer, this is code of the module that gets fired by the search crawler (defined in the scheduler) in order to ask the module for any content that needs to be available in the site search, this is why you get the error even without visiting the page.

**Comment by thosalbert** [comment] 2019-10-14 21:02
Thanks Valades - Any Idea what the problem is and how to fix it?

**Comment by valadas** [comment] 2019-10-15 14:28
Not without digging deeper in to the code which I cannot do right now, but my guess would be something is null that should not be in this code block:

https://github.com/DNNCommunity/DNN.Announcements/blob/6ecb941b34a12e8ca18e0a59db5d53d4e5754147/Components/Business/AnnouncementsController.cs#L254

**Comment by valadas** [comment] 2020-02-13 19:48
Since I cannot reproduce this issue and we have no new information since October, I am closing this issue. If there is any new information that can help pinpoint the issue, please comment and I will be able to reopen. This could maybe also be a Dnn issue, this module will get a new release soon to support Dnn 9.4.x I would recoment watching for that release and updating both Dnn and this module to see if maybe some other fixes also fix this.

**Closed by valadas** 2020-02-13 19:48 UTC

**Comment by MarinaFishkin** [comment] 2020-10-15 16:41
I had a same error in the Admin Log using DNN 9.07.02 and Announcement module 7.2.3 and I notice if in setting set the value for History(days) the error the error disappears.

**Comment by Carolyn-Novak** [comment] 2021-04-29 14:08
I'm having the same issue using DNN 9.9

**Comment by valadas** [comment] 2021-04-29 23:33
Hmm, interesting, my guess is that there was some invalid value in there...

**Comment by Carolyn-Novak** [comment] 2021-04-30 15:36
Thank you!
