### ISSUE TITLE
Where are the Templates?

### ISSUE THREAD

**Issue by jwolner** [DNNCommunity/DNN.Announcements#29] opened 2018-11-05 23:07 UTC
Templates used to be in the Settings of the instance of Announcements to update(v4.0.3)

Not finding where to update the templates.  We want to remove the [PublishDate], but are unsure where to do that exactly.

**Comment by dotcom9** [comment] 2019-01-20 13:04
I have the same issue, DNN 9.1.1, Announcements 7.2.1. No way to edit the item template. The upgrade has broken my layout.

**Comment by valadas** [comment] 2020-02-13 18:48
It looks like there is an issue saving templates as described in #27 I will close this one as a duplicate of #27

**Closed by valadas** 2020-02-13 18:48 UTC
