### ISSUE TITLE
General Exception Error

### ISSUE THREAD

**Issue by hansonrf** [DNNCommunity/DNN.Announcements#35] opened 2019-06-16 12:48 UTC
## Describe the bug
![image](https://user-images.githubusercontent.com/51268409/59564159-74353a80-9011-11e9-923c-5912e74d4a1d.png)

Every minute or so.

## Software Versions
- DNN: 09.03.2.24
- Announcements Module: 07.02.01

Cache cleared
App restarted
Reoccurs immediately.  Just started today.

**Comment by valadas** [comment] 2020-02-13 19:37
Unfortunately I cannot reproduce, this could be a Dnn issue or a data issue on some specific announcements. Please check the /Portal/_default/logs folder and look if you have more information there that maybe could make this issue actionable. I am closing it for now, but if you have more info, you can comment here and I will be happy to reopen.

**Closed by valadas** 2020-02-13 19:37 UTC
